{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","metadata":{"id":"iddr898m1gYb"},"source":["# Errors and Exceptions"]},{"cell_type":"markdown","metadata":{"id":"f3I624mu1gYc"},"source":["No matter your skill as a programmer, you will eventually make a coding mistake.\n","Such mistakes come in three basic flavors:\n","\n","- *Syntax errors:* Errors where the code is not valid Python (generally easy to fix)\n","- *Runtime errors:* Errors where syntactically valid code fails to execute, perhaps due to invalid user input (sometimes easy to fix)\n","- *Semantic errors:* Errors in logic: code executes without a problem, but the result is not what you expect (often very difficult to track-down and fix)\n","\n","Here we're going to focus on how to deal cleanly with *runtime errors*.\n","As we'll see, Python handles runtime errors via its *exception handling* framework."]},{"cell_type":"markdown","metadata":{"id":"DiEVbHl81gYd"},"source":["## Runtime Errors\n","\n","If you've done any coding in Python, you've likely come across runtime errors.\n","They can happen in a lot of ways.\n","\n","For example, if you try to reference an undefined variable:"]},{"cell_type":"code","metadata":{"id":"rA5D9WrE1gYe","colab":{"base_uri":"https://localhost:8080/","height":168},"outputId":"42ca1750-f75f-44d5-93f8-4d4f7deb65f1"},"source":["print(Q)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-cbf1bd89097d>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mQ\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'Q' is not defined"]}]},{"cell_type":"markdown","metadata":{"id":"lpvp8vFB1gYg"},"source":["Or if you try an operation that's not defined:"]},{"cell_type":"code","metadata":{"id":"KWh21xzW1gYh","outputId":"8163e6d5-8257-47e6-8fa5-fed61598444e"},"source":["1 + 'abc'"],"execution_count":null,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"unsupported operand type(s) for +: 'int' and 'str'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-aab9e8ede4f7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;36m1\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m'abc'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for +: 'int' and 'str'"]}]},{"cell_type":"markdown","metadata":{"id":"1TCZaPZK1gYi"},"source":["Or you might be trying to compute a mathematically ill-defined result:"]},{"cell_type":"code","metadata":{"id":"HqTkDwwR1gYj","outputId":"522c6a1f-655b-4fe4-9537-07826d09ffec"},"source":["2 / 0"],"execution_count":null,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-5-ae0c5d243292>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;36m2\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"markdown","metadata":{"id":"M8P-tY551gYl"},"source":["Or maybe you're trying to access a sequence element that doesn't exist:"]},{"cell_type":"code","metadata":{"id":"PfwrzLaU1gYm","outputId":"7afd0816-d466-4e26-d8f7-e7d7ccf60a4d"},"source":["L = [1, 2, 3]\n","L[1000]"],"execution_count":null,"outputs":[{"output_type":"error","ename":"IndexError","evalue":"list index out of range","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-6-06b6eb1b8957>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mL\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m3\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mL\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m1000\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mIndexError\u001b[0m: list index out of range"]}]},{"cell_type":"markdown","metadata":{"id":"GuicM75t1gYn"},"source":["Note that in each case, Python is kind enough to not simply indicate that an error happened, but to spit out a *meaningful* exception that includes information about what exactly went wrong, along with the exact line of code where the error happened.\n","Having access to meaningful errors like this is immensely useful when trying to trace the root of problems in your code."]},{"cell_type":"markdown","metadata":{"id":"hH_dB1G91gYo"},"source":["## Catching Exceptions: ``try`` and ``except``\n","The main tool Python gives you for handling runtime exceptions is the ``try``...``except`` clause.\n","Its basic structure is this:"]},{"cell_type":"code","metadata":{"id":"eBX0N9Lo1gYp","outputId":"1f454372-6193-4149-b57b-8a830fd52822"},"source":["try:\n","    print(\"this gets executed first\")\n","except:\n","    print(\"this gets executed only if there is an error\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["this gets executed first\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"7hqMLwuR1gYq"},"source":["Note that the second block here did not get executed: this is because the first block did not return an error.\n","Let's put a problematic statement in the ``try`` block and see what happens:"]},{"cell_type":"code","metadata":{"id":"P9BrhDK01gYq","outputId":"0f927024-b5a6-4af3-af77-29476f3d2bda"},"source":["try:\n","    print(\"let's try something:\")\n","    x = 1 / 0 # ZeroDivisionError\n","except:\n","    print(\"something bad happened!\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["let's try something:\n","something bad happened!\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"wNAsJHgj1gYr"},"source":["Here we see that when the error was raised in the ``try`` statement (in this case, a ``ZeroDivisionError``), the error was caught, and the ``except`` statement was executed.\n","\n","One way this is often used is to check user input within a function or another piece of code.\n","For example, we might wish to have a function that catches zero-division and returns some other value, perhaps a suitably large number like $10^{100}$:"]},{"cell_type":"code","metadata":{"id":"vbTkgsR41gYr"},"source":["def safe_divide(a, b):\n","    try:\n","        return a / b\n","    except:\n","        return 1E100"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"GsHdQESt1gYs","outputId":"2680b8c6-0b17-418f-c9df-a78a6e46b65e"},"source":["safe_divide(1, 2)"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["0.5"]},"metadata":{"tags":[]},"execution_count":10}]},{"cell_type":"code","metadata":{"id":"6dVHBFCg1gYs","outputId":"243201d9-5306-4df8-9cb3-50c2bc040a4f"},"source":["safe_divide(2, 0)"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["1e+100"]},"metadata":{"tags":[]},"execution_count":11}]},{"cell_type":"markdown","metadata":{"id":"mvWjaLYo1gYt"},"source":["There is a subtle problem with this code, though: what happens when another type of exception comes up? For example, this is probably not what we intended:"]},{"cell_type":"code","metadata":{"id":"ILGOhKBV1gYt","outputId":"a14a0e66-872b-4620-e672-75089c3cd9e2"},"source":["safe_divide (1, '2')"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["1e+100"]},"metadata":{"tags":[]},"execution_count":12}]},{"cell_type":"markdown","metadata":{"id":"Tsw-6nEF1gYu"},"source":["Dividing an integer and a string raises a ``TypeError``, which our over-zealous code caught and assumed was a ``ZeroDivisionError``!\n","For this reason, it's nearly always a better idea to catch exceptions *explicitly*:"]},{"cell_type":"code","metadata":{"id":"0SbG7Olx1gYu"},"source":["def safe_divide(a, b):\n","    try:\n","        return a / b\n","    except ZeroDivisionError:\n","        return 1E100"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"19sngqrY1gYu","outputId":"6ce8f6ea-95d6-4c5b-d071-d88764940b02"},"source":["safe_divide(1, 0)"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["1e+100"]},"metadata":{"tags":[]},"execution_count":14}]},{"cell_type":"code","metadata":{"id":"sahYvmXM1gYv","outputId":"c3eaf183-9cea-4ba6-dc1a-1758b2dd4d2f"},"source":["safe_divide(1, '2')"],"execution_count":null,"outputs":[{"output_type":"error","ename":"TypeError","evalue":"unsupported operand type(s) for /: 'int' and 'str'","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-15-2331af6a0acf>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0msafe_divide\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'2'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-13-10b5f0163af8>\u001b[0m in \u001b[0;36msafe_divide\u001b[0;34m(a, b)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0msafe_divide\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0ma\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0;36m1E100\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTypeError\u001b[0m: unsupported operand type(s) for /: 'int' and 'str'"]}]},{"cell_type":"markdown","metadata":{"id":"v1GKdgtH1gYw"},"source":["We're now catching zero-division errors only, and letting all other errors pass through un-modified."]},{"cell_type":"markdown","metadata":{"id":"Pm83_sth1gYw"},"source":["## Raising Exceptions: ``raise``\n","We've seen how valuable it is to have informative exceptions when using parts of the Python language.\n","It's equally valuable to make use of informative exceptions within the code you write, so that users of your code (foremost yourself!) can figure out what caused their errors.\n","\n","The way you raise your own exceptions is with the ``raise`` statement. For example:"]},{"cell_type":"code","metadata":{"id":"MBveouQX1gYx","outputId":"f61776bf-104a-4453-de3d-6dfd40c5aa28"},"source":["raise RuntimeError(\"my error message\")"],"execution_count":null,"outputs":[{"output_type":"error","ename":"RuntimeError","evalue":"my error message","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-16-c6a4c1ed2f34>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"my error message\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m: my error message"]}]},{"cell_type":"markdown","metadata":{"id":"4c1XGAkq1gYx"},"source":["As an example of where this might be useful, let's return to our ``fibonacci`` function that we defined previously:"]},{"cell_type":"code","metadata":{"id":"BXO9WpJ81gYy"},"source":["def fibonacci(N):\n","    L = []\n","    a, b = 0, 1\n","    while len(L) < N:\n","        a, b = b, a + b\n","        L.append(a)\n","    return L"],"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"tCqtkGWo1gYy"},"source":["One potential problem here is that the input value could be negative.\n","This will not currently cause any error in our function, but we might want to let the user know that a negative ``N`` is not supported.\n","Errors stemming from invalid parameter values, by convention, lead to a ``ValueError`` being raised:"]},{"cell_type":"code","metadata":{"id":"mQTeIT_p1gYz"},"source":["def fibonacci(N):\n","    if N < 0:\n","        raise ValueError(\"N must be non-negative\")\n","    L = []\n","    a, b = 0, 1\n","    while len(L) < N:\n","        a, b = b, a + b\n","        L.append(a)\n","    return L"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"pX-4JVCg1gY0","outputId":"d0f5d5bc-24c5-4013-898e-85454c7dbd88"},"source":["fibonacci(10)"],"execution_count":null,"outputs":[{"output_type":"execute_result","data":{"text/plain":["[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]"]},"metadata":{"tags":[]},"execution_count":19}]},{"cell_type":"code","metadata":{"id":"5zYa1veL1gY1","outputId":"3930a5e8-f59f-4bdb-bce2-7c48c0666cbd"},"source":["fibonacci(-10)"],"execution_count":null,"outputs":[{"output_type":"error","ename":"ValueError","evalue":"N must be non-negative","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-20-3d291499cfa7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mfibonacci\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-18-01d0cf168d63>\u001b[0m in \u001b[0;36mfibonacci\u001b[0;34m(N)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mfibonacci\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mN\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mN\u001b[0m \u001b[0;34m<\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"N must be non-negative\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m     \u001b[0mL\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mValueError\u001b[0m: N must be non-negative"]}]},{"cell_type":"markdown","metadata":{"id":"VQ52uKcj1gY2"},"source":["Now the user knows exactly why the input is invalid, and could even use a ``try``...``except`` block to handle it!"]},{"cell_type":"code","metadata":{"id":"Il014IaC1gY2","outputId":"edc8b283-9183-485b-e7b1-8b7e751f8635"},"source":["N = -10\n","try:\n","    print(\"trying this...\")\n","    print(fibonacci(N))\n","except ValueError:\n","    print(\"Bad value: need to do something else\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["trying this...\n","Bad value: need to do something else\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"ki4sFFVI1gY3"},"source":["## Diving Deeper into Exceptions\n","\n","Briefly, I want to mention here some other concepts you might run into.\n","I'll not go into detail on these concepts and how and why to use them, but instead simply show you the syntax so you can explore more on your own."]},{"cell_type":"markdown","metadata":{"id":"_ACPw3YH1gY4"},"source":["### Accessing the error message\n","\n","Sometimes in a ``try``...``except`` statement, you would like to be able to work with the error message itself.\n","This can be done with the ``as`` keyword:"]},{"cell_type":"code","metadata":{"id":"F_mw7IJd1gY6","outputId":"7556857e-129a-4569-82a1-f3628d4c0b65"},"source":["try:\n","    x = 1 / 0\n","except ZeroDivisionError as err:\n","    print(\"Error class is:  \", type(err))\n","    print(\"Error message is:\", err)"],"execution_count":null,"outputs":[{"output_type":"stream","text":["Error class is:   <class 'ZeroDivisionError'>\n","Error message is: division by zero\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"T0DzZDdj1gY7"},"source":["With this pattern, you can further customize the exception handling of your function."]},{"cell_type":"markdown","metadata":{"id":"xwlrDGGH1gY7"},"source":["### Defining custom exceptions\n","In addition to built-in exceptions, it is possible to define custom exceptions through *class inheritance*.\n","For instance, if you want a special kind of ``ValueError``, you can do this:"]},{"cell_type":"code","metadata":{"id":"KgaItwOW1gY8","outputId":"6fb38150-51ac-407a-a8ff-122744b72428"},"source":["class MySpecialError(ValueError):\n","    pass\n","\n","raise MySpecialError(\"here's the message\")"],"execution_count":null,"outputs":[{"output_type":"error","ename":"MySpecialError","evalue":"here's the message","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMySpecialError\u001b[0m                            Traceback (most recent call last)","\u001b[0;32m<ipython-input-23-92c36e04a9d0>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mpass\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mMySpecialError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"here's the message\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mMySpecialError\u001b[0m: here's the message"]}]},{"cell_type":"markdown","metadata":{"id":"PQYAJ1ku1gY9"},"source":["This would allow you to use a ``try``...``except`` block that only catches this type of error:"]},{"cell_type":"code","metadata":{"id":"lmhsPqW61gY-","outputId":"92404983-cd12-44f7-d86d-38c75f3e5300"},"source":["try:\n","    print(\"do something\")\n","    raise MySpecialError(\"[informative error message here]\")\n","except MySpecialError:\n","    print(\"do something else\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["do something\n","do something else\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"PKHItpO81gY_"},"source":["You might find this useful as you develop more customized code."]},{"cell_type":"markdown","metadata":{"id":"yTeRY1z41gY_"},"source":["## ``try``...``except``...``else``...``finally``\n","In addition to ``try`` and ``except``, you can use the ``else`` and ``finally`` keywords to further tune your code's handling of exceptions.\n","The basic structure is this:"]},{"cell_type":"code","metadata":{"id":"4uNrMwQ91gZA","outputId":"97177ea0-17e5-43cb-df69-5de0e4307c89"},"source":["try:\n","    print(\"try something here\")\n","except:\n","    print(\"this happens only if it fails\")\n","else:\n","    print(\"this happens only if it succeeds\")\n","finally:\n","    print(\"this happens no matter what\")"],"execution_count":null,"outputs":[{"output_type":"stream","text":["try something here\n","this happens only if it succeeds\n","this happens no matter what\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"U-i0_0L01gZB"},"source":["The utility of ``else`` here is clear, but what's the point of ``finally``?\n","Well, the ``finally`` clause really is executed *no matter what*: we usually see it used to do some sort of cleanup after an operation completes."]}]}